# Generated by Django 3.2.9 on 2021-11-25 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Tasks',
        ),
        migrations.AlterModelTable(
            name='tasks',
            table='tasks',
        ),
    ]
